# -*- coding: utf-8 -*-
"""media_movel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RiRNmCvgpvsvq-SwnQAl6vjF5I4Dm9YN

## Imports
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/train.csv')
df['date'] = pd.to_datetime(df['date'])

data = df[(df['store']==1) & (df['item']==1)].sort_values('date').reset_index(drop=True)

"""## Nivel 1"""

data['SMA_3'] = data['sales'].rolling(3).mean()
data['SMA_7'] = data['sales'].rolling(7).mean()
data['SMA_30'] = data['sales'].rolling(30).mean()

print("Últimos 10 dias - SMA:")
print(data[['date','sales','SMA_3','SMA_7','SMA_30']].tail(10))

weights = np.arange(1, 8)
data['WMA_7'] = data['sales'].rolling(7).apply(lambda x: np.dot(x, weights)/weights.sum(), raw=True)
data['EMA_7'] = data['sales'].ewm(span=7, adjust=False).mean()

print("\nComparação SMA x WMA x EMA (janela 7):")
print(data[['date','sales','SMA_7','WMA_7','EMA_7']].tail(10))

train = data.iloc[:-14].copy()
test = data.iloc[-14:].copy()

ultimo_sma7 = train['sales'].rolling(7).mean().iloc[-1]
pred_constante = [ultimo_sma7] * 14

mae_const = mean_absolute_error(test['sales'], pred_constante)
rmse_const = np.sqrt(mean_squared_error(test['sales'], pred_constante))

print(f"Baseline Constante (última SMA_7 = {ultimo_sma7:.2f}):")
print(f"MAE: {mae_const:.2f}")
print(f"RMSE: {rmse_const:.2f}")

ultimos_30 = train.tail(30)['sales'].rolling(7).mean().dropna()
x = np.arange(len(ultimos_30))
coef = np.polyfit(x, ultimos_30, 1)

x_futuro = np.arange(len(ultimos_30), len(ultimos_30) + 14)
pred_linear = coef[0] * x_futuro + coef[1]

mae_linear = mean_absolute_error(test['sales'], pred_linear)
rmse_linear = np.sqrt(mean_squared_error(test['sales'], pred_linear))

print(f"\nBaseline Linear (tendência={coef[0]:.2f}):")
print(f"MAE: {mae_linear:.2f}")
print(f"RMSE: {rmse_linear:.2f}")

"""# **Final**"""

print("\n\nCOMPARAÇÃO:")
print(f"Baseline Constante - MAE: {mae_const:.2f} | RMSE: {rmse_const:.2f}")
print(f"Baseline Linear    - MAE: {mae_linear:.2f} | RMSE: {rmse_linear:.2f}")
print(f"\nMelhor modelo: {'Linear' if mae_linear < mae_const else 'Constante'}")