# -*- coding: utf-8 -*-
"""precificacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkbYKTU39m1yMXHyN6AeDGgy7f5KTZhg
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/csv_data_ted.csv')

df['lucro_unitario'] = df['current_price'] - df['cost']
df['lucro_total'] = df['lucro_unitario'] * df['units_sold_last_month']

print("SITUAÇÃO ATUAL")
print(f"Total de produtos: {len(df)}")
print(f"Lucro total mensal: R$ {df['lucro_total'].sum():,.2f}")
print(f"Receita total mensal: R$ {df['revenue_last_month'].sum():,.2f}")

resultados = []

for idx, row in df.iterrows():
    preco = row['current_price']
    custo = row['cost']
    volume = row['units_sold_last_month']
    elast = row['price_elasticity']
    lucro_atual = row['lucro_total']

    melhor_lucro = lucro_atual
    melhor_ajuste = 0

    for ajuste in [-15, -10, -5, 5, 10, 15]:
        novo_preco = preco * (1 + ajuste/100)
        novo_volume = volume * (1 + (ajuste * elast))
        novo_lucro = (novo_preco - custo) * novo_volume

        if novo_lucro > melhor_lucro:
            melhor_lucro = novo_lucro
            melhor_ajuste = ajuste

    ganho = melhor_lucro - lucro_atual

    if abs(melhor_ajuste) > 0 and ganho > 100:
        resultados.append({
            'produto': row['product_name'],
            'categoria': row['category'],
            'preco_atual': preco,
            'ajuste': melhor_ajuste,
            'novo_preco': preco * (1 + melhor_ajuste/100),
            'ganho_mensal': ganho,
            'elasticidade': elast,
            'margem_atual': row['margin_pct']
        })

top = pd.DataFrame(resultados).sort_values('ganho_mensal', ascending=False)

print(f"\nOportunidades encontradas: {len(top)}")

print("TOP 10 OPORTUNIDADES\n")

for i, r in top.head(10).iterrows():
    print(f"{r['produto']}")
    print(f"Categoria: {r['categoria']}")
    print(f"Ajuste: {r['ajuste']:+.0f}% (R$ {r['preco_atual']:.2f} → R$ {r['novo_preco']:.2f})")
    print(f"Ganho: R$ {r['ganho_mensal']:,.2f}/mês")
    print(f"Elasticidade: {r['elasticidade']:.2f}")
    print()

r = top.iloc[0]
prod = df[df['product_name'] == r['produto']].iloc[0]

print(f"SIMULAÇÃO DETALHADA: {r['produto']}\n")
print(f"Preço atual: R$ {prod['current_price']:.2f}")
print(f"Custo: R$ {prod['cost']:.2f}")
print(f"Volume atual: {prod['units_sold_last_month']:.0f} un/mês")
print(f"Elasticidade: {prod['price_elasticity']:.2f}")
print(f"Margem atual: {r['margem_atual']:.1f}%\n")

print("Cenários:")
for ajuste in [-15, -10, -5, 0, 5, 10, 15]:
    novo_preco = prod['current_price'] * (1 + ajuste/100)
    novo_volume = prod['units_sold_last_month'] * (1 + (ajuste * prod['price_elasticity']))
    novo_lucro = (novo_preco - prod['cost']) * novo_volume
    lucro_base = (prod['current_price'] - prod['cost']) * prod['units_sold_last_month']
    ganho = novo_lucro - lucro_base

    marca = " ←" if ajuste == r['ajuste'] else ""
    print(f"{ajuste:+3.0f}%: R$ {novo_preco:>7.2f} | {novo_volume:>6.0f} un | Lucro R$ {novo_lucro:>9,.2f} | Ganho R$ {ganho:>8,.2f}{marca}")

print(f"\nRecomendação: {r['ajuste']:+.0f}%")
if r['ajuste'] > 0:
    print("Razão: Produto inelástico, volume cai pouco com aumento")
else:
    print("Razão: Produto elástico, redução aumenta muito o volume")

for idx in range(1, 5):
    r = top.iloc[idx]
    prod = df[df['product_name'] == r['produto']].iloc[0]

    print(f"\n{'='*60}")
    print(f"PRODUTO {idx+1}: {r['produto']}")
    print(f"{'='*60}\n")
    print(f"Preço: R$ {prod['current_price']:.2f} | Volume: {prod['units_sold_last_month']:.0f} un")
    print(f"Elasticidade: {prod['price_elasticity']:.2f} | Margem: {r['margem_atual']:.1f}%\n")

    for ajuste in [-15, -10, -5, 0, 5, 10, 15]:
        novo_preco = prod['current_price'] * (1 + ajuste/100)
        novo_volume = prod['units_sold_last_month'] * (1 + (ajuste * prod['price_elasticity']))
        novo_lucro = (novo_preco - prod['cost']) * novo_volume
        lucro_base = (prod['current_price'] - prod['cost']) * prod['units_sold_last_month']
        ganho = novo_lucro - lucro_base

        marca = " ←" if ajuste == r['ajuste'] else ""
        print(f"{ajuste:+3.0f}%: R$ {novo_preco:>7.2f} | {novo_volume:>6.0f} un | Lucro R$ {novo_lucro:>9,.2f} | Ganho R$ {ganho:>8,.2f}{marca}")

    print(f"\nRecomendação: {r['ajuste']:+.0f}%")

ganho_total_top10 = top.head(10)['ganho_mensal'].sum()
ganho_total_top5 = top.head(5)['ganho_mensal'].sum()
lucro_atual_total = df['lucro_total'].sum()

print("\nRESUMO EXECUTIVO")
print("="*60)
print(f"\nImpacto Top 10:")
print(f"Ganho mensal: R$ {ganho_total_top10:,.2f}")
print(f"Ganho anual: R$ {ganho_total_top10*12:,.2f}")
print(f"Aumento no lucro total: {(ganho_total_top10/lucro_atual_total)*100:.1f}%")

print(f"\nImpacto Top 5:")
print(f"Ganho mensal: R$ {ganho_total_top5:,.2f}")
print(f"Ganho anual: R$ {ganho_total_top5*12:,.2f}")

print(f"\nDistribuição:")
aumentos = len(top.head(10)[top.head(10)['ajuste']>0])
reducoes = len(top.head(10)[top.head(10)['ajuste']<0])
print(f"Aumentar preço: {aumentos} produtos")
print(f"Reduzir preço: {reducoes} produtos")

print(f"\nPróximos passos:")
print(f"1. Implementar Top 5 produtos")
print(f"2. Monitorar por 30 dias")
print(f"3. Expandir para Top 10")