# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FxGDCZd6leQOA34jkhXuzf1OMjR1aZMi
"""

import pandas as pd

df = pd.read_csv('/content/customer_dataset_csv.txt')

"""Recência: A quando dias fez a ultima compra."""

R = df[['customer_id', 'last_purchase_date', 'days_since_last_purchase']]
R = R.sort_values('last_purchase_date', ascending= False)
display(R)

"""Frequência: quantidades de compras em um periódo."""

print("Compras por cliente em seu período:")
print(df[['customer_id', 'first_purchase_date', 'last_purchase_date', 'total_orders']].head())

first_paid = df['first_purchase_date'].min()
last_paid = df['last_purchase_date'].max()

all_paids_period = df['total_orders'].sum()

print(f'De {first_paid} até {last_paid}')
print(f'Total de compras no período: {all_paids_period}')

"""Valor: Custo total por cliente"""

print(df[['customer_id', 'total_spent']].head(10))

"""**RFV**"""

df['R'] = df['days_since_last_purchase']
df['F'] = df['total_orders']
df['V'] = df['total_spent']

"""OUTLIERS"""

#dados basicos
print(df[['R', 'F', 'V']].describe())

#Outliers
print(f"Recência maior que 170 dias: {len(df[df['R'] > 170])}")
print(f"Frequência maior que 20 pedidos: {len(df[df['F'] > 20])}")
print(f"Valores maiores que 4000: {len(df[df['V'] > 4000])}")
print(f"Bons clientes de valores altos: {len(df[df['V'] > 2000])}")
print(f"Clientes inativos 90+ dias: {len(df[df['R'] > 90])}")
print(f"Clientes fracos 1-2 pedidos: {len(df[df['F'] <= 2])}")

plt.figure(figsize=(8, 6))
plt.scatter(df['F'], df['V'], c=df['R'], cmap='viridis', alpha=0.6, s=50)
plt.colorbar(label='R')
plt.xlabel('F')
plt.ylabel('V')
plt.title('Mapa RFV dos clientes')
plt.show()

"""**Segmentação**  Score Ponderado"""

df['RFV_Score'] = (df['R'] * 0.3) + (df['F'] * 0.3) + (df['V'] * 0.4)

display(df['RFV_Score'])

"""Verificando a segmentação seguinte, ela se da o sentido devido a soma de cada RFV transformada em score, dessa maneira podendo verificar com clareza quais são os clientes mais fiés, caros e frequentes."""